# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.
# Please make sure to check all the converted content, it is your team's responsibility to make sure that the pipeline is still valid and functions as expected.
steps:
- task: CredScan@2
  displayName: "Run CredScan"
  inputs:
    debugMode: false
    batchSize: 20
    toolMajorVersion: "V2"
    searchersFileType: "Skype"
- task: PoliCheck@1
  displayName: "Run PoliCheck"
  condition: and(succeeded(), eq(eq(variables['Build.SourceBranch'], 'refs/heads/main'), false))
  inputs:
    targetType: F
    SOMEnabled: true
    optionsFC: 0
    optionsXS: 0
    optionsHMENABLE: 0
    continueOnError: true